build: fix typo in dockerfile conf file indexing

diff --git a/.github/workflows/build-check-deploy.yml b/.github/workflows/build-check-deploy.yml
--- a/.github/workflows/build-check-deploy.yml
+++ b/.github/workflows/build-check-deploy.yml
@@ -30,7 +30,6 @@ jobs:
         uses: actions/checkout@v4
       - name: Build Verdaccio Docker Image
         run: |
-          cat common/Dockerfile
           cd verdaccio
           touch conf/htpasswd
           echo ${{ secrets.HTPASSWD }} >> conf/htpasswd
@@ -68,28 +67,30 @@ jobs:
 
   verdaccio-build:
     runs-on: ubuntu-latest
+    needs:
+      - verdaccio-service-up
     steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-      - name: Build Verdaccio Docker Image
-        run: |
-          cd verdaccio
-          touch conf/htpasswd
-          echo ${{ secrets.HTPASSWD }} >> conf/htpasswd
-          docker build -t c-verdaccio .
-          docker run -d --name verdaccio -p 4873:4873 c-verdaccio
-      - name: Wait for Verdaccio to be ready
-        run: |
-          for i in {1..30}; do
-            if curl --silent --fail http://localhost:4873/-/ping; then
-              echo "Verdaccio is ready!"
-              exit 0
-            fi
-            echo "Waiting for Verdaccio..."
-            sleep 2
-          done
-          echo "Verdaccio did not start in time" >&2
-          exit 1
+#      - name: Checkout repository
+#        uses: actions/checkout@v4
+#      - name: Build Verdaccio Docker Image
+#        run: |
+#          cd verdaccio
+#          touch conf/htpasswd
+#          echo ${{ secrets.HTPASSWD }} >> conf/htpasswd
+#          docker build -t c-verdaccio .
+#          docker run -d --name verdaccio -p 4873:4873 c-verdaccio
+#      - name: Wait for Verdaccio to be ready
+#        run: |
+#          for i in {1..30}; do
+#            if curl --silent --fail http://localhost:4873/-/ping; then
+#              echo "Verdaccio is ready!"
+#              exit 0
+#            fi
+#            echo "Waiting for Verdaccio..."
+#            sleep 2
+#          done
+#          echo "Verdaccio did not start in time" >&2
+#          exit 1
       - name: Configure npm to use Verdaccio
         run: |
           echo "//localhost:4873/:_authToken=\"${{ secrets.VERDACCIO_PASSWD }}\"" > ~/.npmrc
